apiVersion: apps/v1
kind: Deployment
metadata:
  name: MenuManagement
  labels:
    app: MenuManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuManagement
  template:
    metadata:
      labels:
        app: MenuManagement
    spec:
      containers:
        - name: MenuManagement
          image: "username/MenuManagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
